task:
  name: "Admin Builder"
  skip: $CIRRUS_BRANCH == 'master'
  only_if: $CIRRUS_USER_PERMISSION == 'admin'
  stateful: true
  timeout_in: 120m
  container:
    image: anggit86/ubuntu:22.04
    cpu: 8
    memory: 32G

  Cek-Pengguna_script:
     - nproc
     - bash -c "$(curl -sL https://raw.githubusercontent.com/NFS-Project/cirrus-ci-skrip/master/rom/checks.sh)"

  SSH_background_script:
     - mkdir -p -m 0700 /root/.ssh
     - cd /root/.ssh
     - curl $SSH_KEY -o id_rsa
     - curl $PUB_KEY -o id_rsa.pub
     - curl $KNOWN_HOSTS -o known_hosts
     - chmod 0600 id_rsa
     - chmod 0600 id_rsa.pub

  Memuat-Ccache_background_script:
     - bash -c "$(curl -sL https://raw.githubusercontent.com/NFS-Project/cirrus-ci-skrip/master/rom/load_ccache.sh)"

  Sinkronasi-rom_script:
     - bash -c "$(curl -sL https://raw.githubusercontent.com/NFS-Project/cirrus-ci-skrip/master/rom/sync.sh)"
     
  Membangun-rom_script:
     - bash -c "$(curl -sL https://raw.githubusercontent.com/NFS-Project/cirrus-ci-skrip/master/rom/building.sh)"
     
  Ccache-informasi_background_script:
     - set -e
     - export CCACHE_DIR=$WORKDIR/ccache
     - ccache -s

  Mengunggah-build_script:
     - bash -c "$(curl -sL https://raw.githubusercontent.com/NFS-Project/cirrus-ci-skrip/master/rom/ziping.sh)"

task:
  name: "User Builder"
  skip: $CIRRUS_BRANCH == 'master'
  only_if: $CIRRUS_USER_PERMISSION == 'write'
  stateful: true
  timeout_in: 120m
  container:
    image: anggit86/ubuntu:22.04
    cpu: 8
    memory: 32G

  Cek-Pengguna_script:
     - nproc
     - bash -c "$(curl -sL https://raw.githubusercontent.com/NFS-Project/cirrus-ci-skrip/master/rom/checks.sh)"

  SSH_background_script:
     - mkdir -p -m 0700 /root/.ssh
     - cd /root/.ssh
     - curl $SSH_KEY -o id_rsa
     - curl $PUB_KEY -o id_rsa.pub
     - curl $KNOWN_HOSTS -o known_hosts
     - chmod 0600 id_rsa
     - chmod 0600 id_rsa.pub

  Memuat-Ccache_background_script:
     - bash -c "$(curl -sL https://raw.githubusercontent.com/NFS-Project/cirrus-ci-skrip/master/rom/load_ccache.sh)"

  Sinkronasi-rom_script:
     - bash -c "$(curl -sL https://raw.githubusercontent.com/NFS-Project/cirrus-ci-skrip/master/rom/sync.sh)"
     
  Membangun-rom_script:
     - bash -c "$(curl -sL https://raw.githubusercontent.com/NFS-Project/cirrus-ci-skrip/master/rom/building.sh)"
     
  Ccache-informasi_background_script:
     - set -e
     - export CCACHE_DIR=$WORKDIR/ccache
     - ccache -s

  Mengunggah-build_script:
     - bash -c "$(curl -sL https://raw.githubusercontent.com/NFS-Project/cirrus-ci-skrip/master/rom/ziping.sh)"
